// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialGoal.Web.Data;

#nullable disable

namespace SocialGoal.Web.Data.Migrations
{
    [DbContext(typeof(SocialGoalDbContext))]
    partial class SocialGoalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialGoal.Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool?>("Activated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CommentText")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UpdateId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("UpdateId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.CommentUser", b =>
                {
                    b.Property<int>("CommentUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentUserId"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentUserId");

                    b.ToTable("CommentUsers", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Focus", b =>
                {
                    b.Property<int>("FocusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FocusId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FocusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("FocusId");

                    b.HasIndex("GroupId");

                    b.ToTable("Foci", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.FollowRequest", b =>
                {
                    b.Property<int>("FollowRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowRequestId"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FollowRequestId");

                    b.ToTable("FollowRequests", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.FollowUser", b =>
                {
                    b.Property<int>("FollowUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowUserId"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ApplicationUser_Id")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ApplicationUser_Id1")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FromUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ToUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("FollowUserId");

                    b.HasIndex("ApplicationUser_Id");

                    b.HasIndex("ApplicationUser_Id1");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("FollowUsers", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<int>("GoalStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("GoalType")
                        .HasColumnType("bit");

                    b.Property<int?>("MetricId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<double?>("Target")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("GoalId");

                    b.HasIndex("GoalStatusId");

                    b.HasIndex("MetricId");

                    b.HasIndex("UserId");

                    b.ToTable("Goals", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GoalStatus", b =>
                {
                    b.Property<int>("GoalStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalStatusId"));

                    b.Property<string>("GoalStatusType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GoalStatusId");

                    b.ToTable("GoalStatus", (string)null);

                    b.HasData(
                        new
                        {
                            GoalStatusId = 1,
                            GoalStatusType = "In Progress"
                        },
                        new
                        {
                            GoalStatusId = 2,
                            GoalStatusType = "On Hold"
                        },
                        new
                        {
                            GoalStatusId = 3,
                            GoalStatusType = "Completed"
                        });
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GroupId");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupComment", b =>
                {
                    b.Property<int>("GroupCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupCommentId"));

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupUpdateId")
                        .HasColumnType("int");

                    b.HasKey("GroupCommentId");

                    b.HasIndex("GroupUpdateId");

                    b.ToTable("GroupComments", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupCommentUser", b =>
                {
                    b.Property<int>("GroupCommentUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupCommentUserId"));

                    b.Property<int>("GroupCommentId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupCommentUserId");

                    b.ToTable("GroupCommentUsers", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupGoal", b =>
                {
                    b.Property<int>("GroupGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupGoalId"));

                    b.Property<int?>("AssignedGroupUserId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("FocusId")
                        .HasColumnType("int");

                    b.Property<string>("GoalName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GoalStatusId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("GroupUserId")
                        .HasColumnType("int");

                    b.Property<int?>("MetricId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<double?>("Target")
                        .HasColumnType("float");

                    b.HasKey("GroupGoalId");

                    b.HasIndex("FocusId");

                    b.HasIndex("GoalStatusId");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupUserId");

                    b.HasIndex("MetricId");

                    b.ToTable("GroupGoals", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupInvitation", b =>
                {
                    b.Property<int>("GroupInvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupInvitationId"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<string>("FromUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ToUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupInvitationId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupInvitations", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupRequest", b =>
                {
                    b.Property<int>("GroupRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupRequestId"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("GroupRequestId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupRequests", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupUpdate", b =>
                {
                    b.Property<int>("GroupUpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupUpdateId"));

                    b.Property<int>("GroupGoalId")
                        .HasColumnType("int");

                    b.Property<double?>("Status")
                        .HasColumnType("float")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Updatemsg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupUpdateId");

                    b.HasIndex("GroupGoalId");

                    b.ToTable("GroupUpdates", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupUpdateSupport", b =>
                {
                    b.Property<int>("GroupUpdateSupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupUpdateSupportId"));

                    b.Property<int>("GroupUpdateId")
                        .HasColumnType("int");

                    b.Property<int>("GroupUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateSupportedDate")
                        .HasColumnType("datetime");

                    b.HasKey("GroupUpdateSupportId");

                    b.HasIndex("GroupUpdateId");

                    b.ToTable("GroupUpdateSupports", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupUpdateUser", b =>
                {
                    b.Property<int>("GroupUpdateUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupUpdateUserId"));

                    b.Property<int>("GroupUpdateId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupUpdateUserId");

                    b.ToTable("GroupUpdateUsers", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupUser", b =>
                {
                    b.Property<int>("GroupUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupUserId"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupUserId");

                    b.ToTable("GroupUsers", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.IdentityUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("User_Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.IdentityUserLogin", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserId", "LoginProvider", "ProviderKey");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.IdentityUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Metric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetricId"));

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MetricId");

                    b.ToTable("Metrics", (string)null);

                    b.HasData(
                        new
                        {
                            MetricId = 1,
                            Type = "%"
                        },
                        new
                        {
                            MetricId = 2,
                            Type = "$"
                        },
                        new
                        {
                            MetricId = 3,
                            Type = "$ M"
                        },
                        new
                        {
                            MetricId = 4,
                            Type = "Rs"
                        },
                        new
                        {
                            MetricId = 5,
                            Type = "Hours"
                        },
                        new
                        {
                            MetricId = 6,
                            Type = "Km"
                        },
                        new
                        {
                            MetricId = 7,
                            Type = "Kg"
                        },
                        new
                        {
                            MetricId = 8,
                            Type = "Years"
                        });
                });

            modelBuilder.Entity("SocialGoal.Web.Data.RegistrationToken", b =>
                {
                    b.Property<int>("RegistrationTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationTokenId"));

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RegistrationTokenId");

                    b.ToTable("RegistrationTokens", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.SecurityToken", b =>
                {
                    b.Property<int>("SecurityTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecurityTokenId"));

                    b.Property<int>("ActualID")
                        .HasColumnType("int");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SecurityTokenId");

                    b.ToTable("SecurityTokens", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Support", b =>
                {
                    b.Property<int>("SupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportId"));

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SupportedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupportId");

                    b.HasIndex("GoalId");

                    b.ToTable("Supports", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.SupportInvitation", b =>
                {
                    b.Property<int>("SupportInvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportInvitationId"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<string>("FromUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ToUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupportInvitationId");

                    b.HasIndex("GoalId");

                    b.ToTable("SupportInvitations", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Update", b =>
                {
                    b.Property<int>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdateId"));

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<double?>("Status")
                        .HasColumnType("float")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Updatemsg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UpdateId");

                    b.HasIndex("GoalId");

                    b.ToTable("Updates", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.UpdateSupport", b =>
                {
                    b.Property<int>("UpdateSupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdateSupportId"));

                    b.Property<int>("UpdateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateSupportedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UpdateSupportId");

                    b.HasIndex("UpdateId");

                    b.ToTable("UpdateSupports", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserProfileId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("ContactNo")
                        .HasColumnType("float");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateEdited")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("ZipCode")
                        .HasColumnType("float");

                    b.HasKey("UserProfileId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Comment", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.Update", "Update")
                        .WithMany("Comments")
                        .HasForeignKey("UpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Update_Comments");

                    b.Navigation("Update");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Focus", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.Group", "Group")
                        .WithMany("Foci")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Group_Foci");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.FollowUser", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.ApplicationUser", null)
                        .WithMany("FollowFromUser")
                        .HasForeignKey("ApplicationUser_Id")
                        .HasConstraintName("ApplicationUser_FollowFromUser");

                    b.HasOne("SocialGoal.Web.Data.ApplicationUser", null)
                        .WithMany("FollowToUser")
                        .HasForeignKey("ApplicationUser_Id1")
                        .HasConstraintName("ApplicationUser_FollowToUser");

                    b.HasOne("SocialGoal.Web.Data.ApplicationUser", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .HasConstraintName("FollowUser_FromUser");

                    b.HasOne("SocialGoal.Web.Data.ApplicationUser", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .HasConstraintName("FollowUser_ToUser");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Goal", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.GoalStatus", "GoalStatus")
                        .WithMany("Goals")
                        .HasForeignKey("GoalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("GoalStatus_Goals");

                    b.HasOne("SocialGoal.Web.Data.Metric", "Metric")
                        .WithMany("Goals")
                        .HasForeignKey("MetricId")
                        .HasConstraintName("Metric_Goals");

                    b.HasOne("SocialGoal.Web.Data.ApplicationUser", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .HasConstraintName("ApplicationUser_Goals");

                    b.Navigation("GoalStatus");

                    b.Navigation("Metric");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupComment", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.GroupUpdate", "GroupUpdate")
                        .WithMany("GroupComments")
                        .HasForeignKey("GroupUpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("GroupComment_GroupUpdate");

                    b.Navigation("GroupUpdate");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupGoal", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.Focus", "Focus")
                        .WithMany("GroupGoals")
                        .HasForeignKey("FocusId")
                        .HasConstraintName("Focus_GroupGoals");

                    b.HasOne("SocialGoal.Web.Data.GoalStatus", "GoalStatus")
                        .WithMany("GroupGoals")
                        .HasForeignKey("GoalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("GroupGoal_GoalStatus");

                    b.HasOne("SocialGoal.Web.Data.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("GroupGoal_Group");

                    b.HasOne("SocialGoal.Web.Data.GroupUser", "GroupUser")
                        .WithMany("GroupGoals")
                        .HasForeignKey("GroupUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("GroupUser_GroupGoals");

                    b.HasOne("SocialGoal.Web.Data.Metric", "Metric")
                        .WithMany("GroupGoals")
                        .HasForeignKey("MetricId")
                        .HasConstraintName("Metric_GroupGoals");

                    b.Navigation("Focus");

                    b.Navigation("GoalStatus");

                    b.Navigation("Group");

                    b.Navigation("GroupUser");

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupInvitation", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.Group", "Group")
                        .WithMany("GroupInvitations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("GroupInvitation_Group");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupRequest", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.Group", "Group")
                        .WithMany("GroupRequests")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("GroupRequest_Group");

                    b.HasOne("SocialGoal.Web.Data.ApplicationUser", "User")
                        .WithMany("GroupRequests")
                        .HasForeignKey("UserId")
                        .HasConstraintName("ApplicationUser_GroupRequests");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupUpdate", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.GroupGoal", "GroupGoal")
                        .WithMany("Updates")
                        .HasForeignKey("GroupGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("GroupUpdate_GroupGoal");

                    b.Navigation("GroupGoal");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupUpdateSupport", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.GroupUpdate", "GroupUpdate")
                        .WithMany()
                        .HasForeignKey("GroupUpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("GroupUpdateSupport_GroupUpdate");

                    b.Navigation("GroupUpdate");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.IdentityUserClaim", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("IdentityUserClaim_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.IdentityUserLogin", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("IdentityUserLogin_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.IdentityUserRole", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.IdentityRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("IdentityUserRole_Role");

                    b.HasOne("SocialGoal.Web.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("IdentityUserRole_User");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Support", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.Goal", "Goal")
                        .WithMany("Supports")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Support_Goal");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.SupportInvitation", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.Goal", "Goal")
                        .WithMany("SupportInvitations")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("SupportInvitation_Goal");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Update", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.Goal", "Goal")
                        .WithMany("Updates")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Goal_Updates");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.UpdateSupport", b =>
                {
                    b.HasOne("SocialGoal.Web.Data.Update", "Update")
                        .WithMany("UpdateSupports")
                        .HasForeignKey("UpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UpdateSupport_Update");

                    b.Navigation("Update");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.ApplicationUser", b =>
                {
                    b.Navigation("FollowFromUser");

                    b.Navigation("FollowToUser");

                    b.Navigation("Goals");

                    b.Navigation("GroupRequests");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Focus", b =>
                {
                    b.Navigation("GroupGoals");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Goal", b =>
                {
                    b.Navigation("SupportInvitations");

                    b.Navigation("Supports");

                    b.Navigation("Updates");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GoalStatus", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("GroupGoals");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Group", b =>
                {
                    b.Navigation("Foci");

                    b.Navigation("GroupInvitations");

                    b.Navigation("GroupRequests");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupGoal", b =>
                {
                    b.Navigation("Updates");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupUpdate", b =>
                {
                    b.Navigation("GroupComments");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.GroupUser", b =>
                {
                    b.Navigation("GroupGoals");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.IdentityRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Metric", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("GroupGoals");
                });

            modelBuilder.Entity("SocialGoal.Web.Data.Update", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("UpdateSupports");
                });
#pragma warning restore 612, 618
        }
    }
}
